# Generated by Django 5.0.3 on 2024-03-17 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 15, 17, 37, 887844, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
