# Generated by Django 5.0.3 on 2024-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_taskgroup_date_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
